Algoritmo "Mostrar contagem usando Estrutura Enquanto"
// 
//  
// Descrição   : Escreva um programa que mostre na tela a seguinte contagem:
// 6 7 8 9 10 11 Acabou
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/12/2022
Var
// Seção de Declarações das variáveis 
     N : Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
         N <- 6
      Enquanto (N < 12) faca
          Escreva(N)
          N <- N + 1
      FimEnquanto

Fimalgoritmo