Algoritmo "Ola, Mundo"
// 
//  
// Descrição   :  Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
// Autor(a)    : Marcos Monte
// Data atual  : 29/11/2022
Var
// Seção de Declarações das variáveis 
     txt: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreval("===========")
    Escreval("Olá, Mundo!")
    Escreval("===========")

Fimalgoritmo